import {
  User,
  Pet,
  Provider,
  ServiceCategory,
  Booking,
  WalkSession,
  EmergencyIncident,
  SafetyEvent,
  Message,
  Conversation,
  NotificationItem,
  Payment,
  Review,
  PlatformSettings,
  AdminAuditLog,
  AdminBroadcastNotification,
} from '../types/index.ts';

// Initial Seed User (Elena Miller from Stitch design)
export const initialUser: User = {
  id: 'usr_elena_miller',
  name: 'Elena Miller',
  email: 'elena.miller@petcare.internal',
  role: 'USER',
  status: 'Active',
  avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBV4GEe-_MkIoVoeXbDrkHd6cX4fDmMgrR5zx1p6Pd6PMGJwTyfOpUr4HbgeMLZyzQQzKbNTsdrSvqv5Vp-iMy4FOyO9-YG0QIRooIGQuPAsSKesr4TMUlQFeSEYNgpTLCOVjB4pNg1Re1UBEQSBwuO4782sUm94-1ZmTgi0GOrodIDcks-5tYVE3AkI27SRlFAiUyMxCKshvucVoUBzL_aDxWSkjqzeNIkAtPHAFeyYphiQQWroxMA',
  phone: '+1 (555) 0144',
  address: '424 Elm Crest Ave',
  city: 'Seattle, WA',
  emergencyContact: {
    name: 'David Miller',
    relationship: 'Husband',
    phone: '+1 (555) 0199',
  },
  createdAt: '2024-01-15T08:00:00Z',
};

// Platform Administrator Account (Marcus Vance)
export const initialAdminUser: User = {
  id: 'usr_admin_marcus',
  name: 'Marcus Vance',
  email: 'admin@petcare.internal',
  role: 'USER',
  status: 'Active',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400',
  phone: '+1 (555) 0100',
  address: 'PetCare HQ - 100 Pine Street',
  city: 'Seattle, WA',
  emergencyContact: {
    name: 'Platform Operations Center',
    relationship: 'Supervisor',
    phone: '+1 (800) 555-0911',
  },
  createdAt: '2023-11-01T08:00:00Z',
};

// Platform Users List (Shared by Admin and User App)
export const initialUsers: User[] = [
  initialUser,
  {
    id: 'usr_david_miller',
    name: 'David Miller',
    email: 'david.miller@petcare.internal',
    role: 'USER',
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=400',
    phone: '+1 (555) 0199',
    address: '424 Elm Crest Ave',
    city: 'Seattle, WA',
    emergencyContact: { name: 'Elena Miller', relationship: 'Wife', phone: '+1 (555) 0144' },
    createdAt: '2024-02-10T11:20:00Z',
  },
  {
    id: 'usr_jessica_hayes',
    name: 'Jessica Hayes',
    email: 'jessica.hayes@example.com',
    role: 'USER',
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=400',
    phone: '+1 (555) 0288',
    address: '891 Magnolia Blvd',
    city: 'Seattle, WA',
    emergencyContact: { name: 'Tom Hayes', relationship: 'Brother', phone: '+1 (555) 0299' },
    createdAt: '2024-03-05T14:45:00Z',
  },
  {
    id: 'usr_michael_chen',
    name: 'Michael Chen',
    email: 'm.chen@example.com',
    role: 'USER',
    status: 'Active',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=400',
    phone: '+1 (555) 0377',
    address: '142 Queen Anne Hill',
    city: 'Seattle, WA',
    emergencyContact: { name: 'Lisa Chen', relationship: 'Sister', phone: '+1 (555) 0388' },
    createdAt: '2024-03-22T09:10:00Z',
  },
  {
    id: 'usr_samantha_reed',
    name: 'Samantha Reed',
    email: 'sam.reed@example.com',
    role: 'USER',
    status: 'Suspended',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&q=80&w=400',
    phone: '+1 (555) 0466',
    address: '505 Capitol Hill Way',
    city: 'Seattle, WA',
    emergencyContact: { name: 'Robert Reed', relationship: 'Father', phone: '+1 (555) 0477' },
    createdAt: '2024-04-12T16:00:00Z',
  },
];

// Pets (Bruno, Milo, and Luna)
export const initialPets: Pet[] = [
  {
    id: 'pet_bruno',
    userId: 'usr_elena_miller',
    name: 'Bruno',
    species: 'Dog',
    breed: 'Golden Retriever',
    ageYears: 2,
    ageMonths: 6,
    gender: 'Male (Neutered)',
    weightKg: 28.0,
    photoUrl: 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&q=80&w=400',
    healthStatus: 'Healthy',
    microchipId: '985-231-904-551-789',
    activeStatusNote: 'Resting after walk',
    monthlyStats: {
      month: 'Sep 2026',
      kmWalked: 34.6,
      sessions: 18,
      safeZonePercent: 100,
    },
    safetyProfile: {
      safeZoneName: 'Oakwood Green Perimeter',
      safeZoneRadiusKm: 1.0,
      walkerNotes: 'Friendly, responsive to praise, loves yellow tennis balls. Allowed treats: Salmon bites.',
      allowedTreats: 'Salmon bites only',
      allergies: 'None',
      dietaryNotes: 'High-protein salmon & rice kibble.',
    },
    emergencyContacts: [
      {
        name: 'Elena Miller',
        role: 'Primary Parent',
        phone: '+1 555-0144',
        isPrimary: true,
      },
      {
        name: 'Oakwood Vet Hospital',
        role: '24/7 ER Vet',
        phone: '+1 555-0192',
        is24_7Vet: true,
      },
    ],
    vaccinations: [
      {
        name: 'Rabies (3-Year Core)',
        validUntil: 'Dec 2026',
        status: 'Up to Date',
      },
      {
        name: 'DHPP Polyvalent',
        validUntil: 'Jan 2027',
        status: 'Up to Date',
      },
      {
        name: 'Bordetella (Kennel Cough)',
        validUntil: 'Jul 2027',
        status: 'Up to Date',
      },
    ],
  },
  {
    id: 'pet_milo',
    userId: 'usr_elena_miller',
    name: 'Milo',
    species: 'Dog',
    breed: 'Golden Retriever',
    ageYears: 3,
    ageMonths: 2,
    gender: 'Male (Neutered)',
    weightKg: 31.5,
    photoUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCUuQBqBW7jAgvPaf0dm9LxrCEv9Q3L_DyJbjPZweOP62mkqtSQPixUMJLncp0NpElorXOg-p_YisXvtzXfTNqFsBG25ZU9Z9ihdE4058cJ0lITdZ64Okc87t2PDjDxgu0cnVIxZVNHclEB3A2NieX4MOSjjQwWqStQSYaWLbyidVFwtGzgQNI8kWWcz8N2wzqnmchHerCHmiy52SUkrueT70vtdMvOgVP1Oksny7rwXx1emN4y7pU0',
    healthStatus: 'Healthy',
    microchipId: '985-141-002-348-112',
    activeStatusNote: 'On a walk',
    monthlyStats: {
      month: 'May 2024',
      kmWalked: 48.2,
      sessions: 22,
      safeZonePercent: 100,
    },
    safetyProfile: {
      safeZoneName: 'Oakwood Neighborhood Zone',
      safeZoneRadiusKm: 1.0,
      walkerNotes: 'Friendly with big dogs, pulls slightly near squirrels, loves yellow tennis balls. Allowed treats: Salmon bites only.',
      allowedTreats: 'Salmon bites only',
      allergies: 'Mild bee pollen sensitivity during spring',
      dietaryNotes: 'Prescription salmon hypoallergenic kibble only. Avoid chicken by-products.',
    },
    emergencyContacts: [
      {
        name: 'Oakwood Vet Hospital',
        role: '24/7 ER Vet',
        phone: '+1 555-0192',
        is24_7Vet: true,
      },
      {
        name: 'Elena Miller',
        role: 'Primary Parent',
        phone: '+1 555-0144',
        isPrimary: true,
      },
    ],
    vaccinations: [
      {
        name: 'Rabies (3-Year Core)',
        validUntil: 'Nov 2025',
        status: 'Up to Date',
      },
      {
        name: 'DHPP Polyvalent',
        validUntil: 'Mar 2026',
        status: 'Up to Date',
      },
      {
        name: 'Bordetella (Kennel Cough)',
        validUntil: 'Due in 2 weeks (Jun 12)',
        status: 'Due Soon',
        isDue: true,
      },
    ],
  },
  {
    id: 'pet_luna',
    userId: 'usr_elena_miller',
    name: 'Luna',
    species: 'Cat',
    breed: 'British Shorthair',
    ageYears: 2,
    ageMonths: 4,
    gender: 'Female (Spayed)',
    weightKg: 4.8,
    photoUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBAfhN8pHlSG0xor_7MUsRg57jr7pACCb3sFfX3Ja7dlh4NX33Chy_1Z0MnNA3z4C63YkIVgxKb22m_j24klKkoXVc4WrWkfnC4WRPawMYuKsKj7BvY51Qla8QChNKfyBAgyMbQQjHRE2UYsBqy75glp1ykMylKcuom4dBSQAHmnPtFQYweOcQX_iwhpL3k4kk75QuqcKfO6kyXth2mYP7gfZ3Ics7Qpj_DA11AreIUiEFGIzZ6DbkZ',
    healthStatus: 'Healthy',
    microchipId: '985-772-911-304-889',
    activeStatusNote: 'Resting at home',
    monthlyStats: {
      month: 'May 2024',
      kmWalked: 0,
      sessions: 4,
      safeZonePercent: 100,
    },
    safetyProfile: {
      safeZoneName: 'Home Perimeter',
      safeZoneRadiusKm: 0.2,
      walkerNotes: 'Indoor only cat. Very calm, enjoys catnip mice and chin scratches.',
      allowedTreats: 'Freeze-dried tuna flakes',
      allergies: 'None recorded',
      dietaryNotes: 'High-protein grain-free wet food twice daily.',
    },
    emergencyContacts: [
      {
        name: 'Oakwood Vet Hospital',
        role: '24/7 ER Vet',
        phone: '+1 555-0192',
        is24_7Vet: true,
      },
      {
        name: 'Elena Miller',
        role: 'Primary Parent',
        phone: '+1 555-0144',
        isPrimary: true,
      },
    ],
    vaccinations: [
      {
        name: 'FVRCP Core Feline',
        validUntil: 'Jan 2026',
        status: 'Up to Date',
      },
      {
        name: 'Rabies Feline',
        validUntil: 'Aug 2025',
        status: 'Up to Date',
      },
    ],
  },
];

// Service Categories
export const initialServices: ServiceCategory[] = [
  { id: 'srv_dog_walking', name: 'Dog Walking', slug: 'dog-walking', icon: 'directions_walk', description: 'Safe, attentive dog walks with clear service updates.', startingPrice: 25, isVerified: true, isActive: true, durationOptions: [{ minutes: 30, label: '30 min', price: 25 }, { minutes: 45, label: '45 min', price: 35, isPopular: true }, { minutes: 60, label: '60 min', price: 45 }] },
  { id: 'srv_grooming', name: 'Grooming', slug: 'grooming', icon: 'content_cut', description: 'Thoughtful grooming for a clean, comfortable coat.', startingPrice: 55, isVerified: true, isActive: true, durationOptions: [{ minutes: 60, label: 'Standard Groom (60m)', price: 55 }, { minutes: 90, label: 'Deluxe Spa (90m)', price: 80, isPopular: true }] },
  { id: 'srv_training', name: 'Training', slug: 'training', icon: 'sports_score', description: 'Positive-reinforcement training for everyday skills.', startingPrice: 70, isVerified: true, isActive: true },
];

// Verified Providers
export const initialProviders: Provider[] = [
  {
    id: 'prov_sarah_jenkins',
    name: 'Sarah Jenkins',
    title: 'Certified Canine Specialist & Top Walker',
    avatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD9cXKmn56GJpqtV_Wi3GX7Vuv1JGKOZmGPF58ICReaJ8ThIerkLj9jNMa3_VVOfc8RtQBJizlMTe0hZ73iCP8XZnYxzhuNtdAv-9dz4rxLzj-NgN4W2SGqkja0f1ysj59gxF-Iua6RntJmCobUOBsmMkfXGzD3ANHrwVTnINWIHAtCmd7njIgdMB4NMsqEYZKihlBuDUdsq_uJOz2Eg0YRi4CmbyJEkJrFVSynEYdXXPS4R-iHorKW',
    serviceTypes: ['dog-walking', 'training'],
    verificationStatus: 'verified',
    rating: 4.9,
    reviewsCount: 420,
    experienceYears: 5,
    hourlyRate: 35,
    badges: ['GPS Tracked', 'First Aid Cert', 'CPR Trained', 'Top Rated'],
    phone: '+1 (555) 234-8901',
    bio: 'Dedicated professional dog walker and canine first responder. Certified in pet emergency care and reactive dog management with over 5 years of joyful, safe walks.',
    availability: ['08:30 AM', '11:00 AM', '03:00 PM', '05:30 PM'],
    location: 'Oakwood & Surrounding Neighborhoods',
  },
  {
    id: 'prov_chloe_groom',
    name: 'Chloe Rivera',
    title: 'Master Grooming Stylist',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=400',
    serviceTypes: ['grooming'],
    verificationStatus: 'verified',
    rating: 4.8,
    reviewsCount: 185,
    experienceYears: 6,
    hourlyRate: 55,
    badges: ['Hypoallergenic Certified', 'Skin Care Specialist', 'Gentle Handling'],
    phone: '+1 (555) 456-7890',
    bio: 'Patient and loving groomer specializing in double-coated breeds, hypoallergenic herbal baths, and hand-scissored styling.',
    availability: ['09:00 AM', '12:00 PM', '02:30 PM'],
    location: 'Seattle Downtown Salon & Mobile Unit',
    status: 'Active',
  },
  {
    id: 'prov_liam_walker',
    name: 'Liam Walker',
    title: 'Applicant Canine Walker',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&q=80&w=400',
    serviceTypes: ['dog-walking'],
    verificationStatus: 'pending',
    rating: 0,
    reviewsCount: 0,
    experienceYears: 2,
    hourlyRate: 28,
    badges: ['Background Checked Pending', 'CPR Course In-Progress'],
    phone: '+1 (555) 789-0123',
    bio: 'Passionate animal lover applying for neighborhood dog walking. Background check documents submitted.',
    availability: ['08:00 AM', '10:00 AM', '01:00 PM'],
    location: 'Seattle Eastside',
    status: 'Pending',
  },
];

// Initial Bookings
export const initialBookings: Booking[] = [];

// Initial Live Walk Session matching Stitch screen details
export const initialWalkSession: WalkSession = {
  id: 'walk_session_live_01',
  bookingId: 'bk_walk_active_01',
  petId: 'pet_milo',
  walkerId: 'prov_sarah_jenkins',
  walkerName: 'Sarah Jenkins',
  walkerAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAY1t1DV4PHy0RF5sey9x_IGer7BabOrA3npqdbGVYaYloEwWrmNkfBvRZUZy3jaxk44GvU9-XRY9xFXcyi_bhaaB6VjcJMAT10IvoHBVFTcOM6AsIfP9xwai_hFgcAR613b8Vv7NDnCCQcEXpE9pfRyIF8QUMDSnuIFJJAyOUZITxXWjRxDU-P9pu5JRc3WW4fLdWov9c_H2CzE0vY282YEA7M2oVMHAhrOfyf_UKSbe0ilSOkAj4S',
  walkerPhone: '+1 (555) 234-8901',
  petName: 'Milo',
  petAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCUuQBqBW7jAgvPaf0dm9LxrCEv9Q3L_DyJbjPZweOP62mkqtSQPixUMJLncp0NpElorXOg-p_YisXvtzXfTNqFsBG25ZU9Z9ihdE4058cJ0lITdZ64Okc87t2PDjDxgu0cnVIxZVNHclEB3A2NieX4MOSjjQwWqStQSYaWLbyidVFwtGzgQNI8kWWcz8N2wzqnmchHerCHmiy52SUkrueT70vtdMvOgVP1Oksny7rwXx1emN4y7pU0',
  status: 'in_progress',
  startTime: '11:02 AM',
  distanceKm: 2.4,
  activeDurationSeconds: 34 * 60 + 12,
  currentSpeedKmH: 3.4,
  avgPace: "14'15\"",
  walkerBatteryPct: 84,
  collarBatteryPct: 92,
  pottyCounts: {
    pee: 2,
    poop: 1,
  },
  isHydrated: true,
  safeZoneState: 'GREEN',
  distanceToBoundaryM: 380,
  safeZoneRadiusM: 1000,
  currentLocation: {
    lat: 37.7749,
    lng: -122.4194,
    address: 'Oakwood Park South Entrance, Seattle / SF',
  },
  timeline: [
    {
      id: 'tl_1',
      icon: 'water_full',
      title: 'Hydration break given',
      time: '11:28 AM',
      description: 'Sarah offered 250ml fresh water at fountain.',
      type: 'hydration',
    },
    {
      id: 'tl_2',
      icon: 'park',
      title: 'Entered Oakwood Dog Park',
      time: '11:15 AM',
      description: 'Inside designated Safe Zone bounds.',
      type: 'zone',
    },
    {
      id: 'tl_3',
      icon: 'home',
      title: 'Walk started from Home',
      time: '11:02 AM',
      description: '424 Elm Crest Ave · GPS Lock stable',
      type: 'start',
    },
  ],
};

// Initial Emergency Incidents
export const initialEmergencies: EmergencyIncident[] = [
  {
    id: 'emg_001',
    bookingId: 'bk_walk_active_01',
    walkSessionId: 'walk_session_live_01',
    userId: 'usr_elena_miller',
    petId: 'pet_milo',
    walkerId: 'prov_sarah_jenkins',
    timestamp: '2026-09-25T11:32:00Z',
    location: {
      lat: 37.7749,
      lng: -122.4194,
      address: 'Oakwood Park South Entrance (near 4th & Elm St)',
    },
    emergencyType: 'ACCIDENT_DETECTED',
    status: 'Triggered',
    title: 'Sudden Stop Detected',
    description: 'Walker Sarah & Milo stopped unexpectedly near 4th & Elm St for > 4 minutes. Collision/drop sensor triggered.',
    autoDispatchSecondsRemaining: 38,
    contactsNotified: [
      {
        name: 'David Miller',
        relationship: 'Husband',
        phone: '+1 (555) 0199',
        status: 'Delivered',
      },
    ],
    vetClinic: {
      name: 'VCA North Bay Emergency Vet',
      distance: '1.2 miles away',
      phone: '+1 555-987-4411',
      status: 'Open 24 Hours • Trauma Ready',
    },
  },
];

// Initial Conversations & Messages
export const initialConversations: Conversation[] = [
  {
    id: 'conv_sarah',
    participantIds: ['usr_elena_miller', 'prov_sarah_jenkins'],
    providerId: 'prov_sarah_jenkins',
    providerName: 'Sarah Jenkins',
    providerAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD9cXKmn56GJpqtV_Wi3GX7Vuv1JGKOZmGPF58ICReaJ8ThIerkLj9jNMa3_VVOfc8RtQBJizlMTe0hZ73iCP8XZnYxzhuNtdAv-9dz4rxLzj-NgN4W2SGqkja0f1ysj59gxF-Iua6RntJmCobUOBsmMkfXGzD3ANHrwVTnINWIHAtCmd7njIgdMB4NMsqEYZKihlBuDUdsq_uJOz2Eg0YRi4CmbyJEkJrFVSynEYdXXPS4R-iHorKW',
    lastMessageText: "Milo is having a fantastic time at the park! We just stopped for a fresh water break.",
    lastMessageTime: '11:29 AM',
    unreadCount: 1,
  },
  {
    id: 'conv_vet_aris',
    participantIds: ['usr_elena_miller', 'prov_aris_thorne'],
    providerId: 'prov_aris_thorne',
    providerName: 'Dr. Aris Thorne, DVM',
    providerAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAsG3EEUK_BjsZhFaqbIiim_XuKPuVi47F9q6psv_TWdRwhDBrrGtr4AmktKapY1XZB-Wg-KH6aYTw7vOGa7Bkpg2nM3PnAbH0u0wWV9IV5bKHIc9jDr7Pz-5MZlQXaQ9hMjne9NawK7U03qgZ0rZLAjhM3ZOVCe5KPWWfCysPaKsv_hukiQ0eJiov9_idbi70tHT3gIWUcmLTrUuxm4U-MK-okF5noR-rBginmjHxWuEkGqqfjRPc-',
    lastMessageText: 'Confirming our home visit tomorrow at 10:30 AM. Please ensure Milo has fasted for 2 hours if doing bloodwork.',
    lastMessageTime: 'Yesterday',
    unreadCount: 0,
  },
];

export const initialMessages: Record<string, Message[]> = {
  conv_sarah: [
    {
      id: 'msg_1',
      conversationId: 'conv_sarah',
      senderId: 'usr_elena_miller',
      senderName: 'Elena Miller',
      senderAvatar: initialUser.avatar,
      text: 'Hi Sarah! Milo is waiting at the front door. He has his green harness on.',
      timestamp: '10:55 AM',
      isRead: true,
    },
    {
      id: 'msg_2',
      conversationId: 'conv_sarah',
      senderId: 'prov_sarah_jenkins',
      senderName: 'Sarah Jenkins',
      senderAvatar: initialProviders[0].avatar,
      text: 'Good morning Elena! Just arrived. He greeted me with tail wags. Heading out for the Oakwood perimeter walk now!',
      timestamp: '11:02 AM',
      isRead: true,
    },
    {
      id: 'msg_3',
      conversationId: 'conv_sarah',
      senderId: 'prov_sarah_jenkins',
      senderName: 'Sarah Jenkins',
      senderAvatar: initialProviders[0].avatar,
      text: 'Milo is having a fantastic time at the park! We just stopped for a fresh water break.',
      timestamp: '11:29 AM',
      isRead: false,
    },
  ],
  conv_vet_aris: [
    {
      id: 'msg_v1',
      conversationId: 'conv_vet_aris',
      senderId: 'prov_aris_thorne',
      senderName: 'Dr. Aris Thorne, DVM',
      senderAvatar: initialProviders[1].avatar,
      text: 'Confirming our home visit tomorrow at 10:30 AM. Please ensure Milo has fasted for 2 hours if doing bloodwork.',
      timestamp: 'Yesterday, 4:15 PM',
      isRead: true,
    },
  ],
};

// Initial Notifications
export const initialNotifications: NotificationItem[] = [
  {
    id: 'notif_1',
    userId: 'usr_elena_miller',
    type: 'SAFETY_ALERT',
    title: 'Live Walk in Progress',
    message: 'Sarah Jenkins started Milo’s 45 min walk. GPS telemetry is active.',
    isRead: false,
    timestamp: '11:02 AM',
    bookingId: 'bk_walk_active_01',
  },
  {
    id: 'notif_2',
    userId: 'usr_elena_miller',
    type: 'WEATHER_TIP',
    title: 'Hydration & Weather Advisory',
    message: 'Midday heat index is rising in Seattle. Ensure Milo pauses every 20 minutes for water.',
    isRead: false,
    timestamp: '10:30 AM',
  },
  {
    id: 'notif_3',
    userId: 'usr_elena_miller',
    type: 'BOOKING_CONFIRMED',
    title: 'Home Vet Checkup Confirmed',
    message: 'Dr. Aris Thorne is scheduled for tomorrow at 10:30 AM.',
    isRead: true,
    timestamp: 'Yesterday',
    bookingId: 'bk_vet_tomorrow_02',
  },
];

// Initial Payments
export const initialPayments: Payment[] = [
  {
    id: 'pay_live_01',
    bookingId: 'bk_walk_active_01',
    userId: 'usr_elena_miller',
    amount: 37.5,
    currency: 'USD',
    status: 'succeeded',
    paymentMethod: 'card',
    transactionId: 'txn_live_994821',
    timestamp: '2026-09-24T18:30:15Z',
    receiptUrl: '#',
  },
  {
    id: 'pay_vet_02',
    bookingId: 'bk_vet_tomorrow_02',
    userId: 'usr_elena_miller',
    amount: 100.0,
    currency: 'USD',
    status: 'pending',
    paymentMethod: 'card',
    transactionId: 'txn_vet_448201',
    timestamp: '2026-09-23T14:15:20Z',
    receiptUrl: '#',
  },
  {
    id: 'pay_past_03',
    bookingId: 'bk_grooming_past_03',
    userId: 'usr_elena_miller',
    amount: 83.0,
    currency: 'USD',
    status: 'succeeded',
    paymentMethod: 'apple_pay',
    transactionId: 'txn_grm_837192',
    timestamp: '2026-09-16T11:00:10Z',
    receiptUrl: '#',
  },
  {
    id: 'pay_ref_04',
    bookingId: 'bk_cancelled_04',
    userId: 'usr_jessica_hayes',
    amount: 45.0,
    currency: 'USD',
    status: 'refunded',
    paymentMethod: 'card',
    transactionId: 'txn_ref_102938',
    timestamp: '2026-09-21T09:20:00Z',
    receiptUrl: '#',
  },
  {
    id: 'pay_fail_05',
    bookingId: 'bk_failed_05',
    userId: 'usr_michael_chen',
    amount: 65.0,
    currency: 'USD',
    status: 'failed',
    paymentMethod: 'google_pay',
    transactionId: 'txn_fail_554821',
    timestamp: '2026-09-22T17:40:00Z',
    receiptUrl: '#',
  },
];

// Initial Reviews & Moderation
export const initialReviews: Review[] = [
  {
    id: 'rev_1',
    bookingId: 'bk_walk_past_1',
    providerId: 'prov_sarah_jenkins',
    providerName: 'Sarah Jenkins',
    serviceName: 'Dog Walking (Oakwood Park)',
    userId: 'usr_elena_miller',
    userName: 'Elena Miller',
    userAvatar: initialUser.avatar,
    rating: 5,
    comment: 'Sarah is absolute magic with Milo! The live GPS radar and potty logs gave me total peace of mind at work.',
    createdAt: '2026-09-20T15:30:00Z',
    status: 'Published',
  },
  {
    id: 'rev_2',
    bookingId: 'bk_vet_past_2',
    providerId: 'prov_aris_thorne',
    providerName: 'Dr. Aris Thorne, DVM',
    serviceName: 'Veterinary Home Visit',
    userId: 'usr_elena_miller',
    userName: 'Elena Miller',
    userAvatar: initialUser.avatar,
    rating: 5,
    comment: 'Gentle, prompt, and thoroughly answered all my vaccination questions. Zero clinic waiting stress!',
    createdAt: '2026-09-12T11:15:00Z',
    status: 'Published',
  },
  {
    id: 'rev_3',
    bookingId: 'bk_groom_past_3',
    providerId: 'prov_chloe_groom',
    providerName: 'Chloe Rivera',
    serviceName: 'Deluxe Grooming Spa',
    userId: 'usr_jessica_hayes',
    userName: 'Jessica Hayes',
    userAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=400',
    rating: 4,
    comment: 'Charlie looked fabulous and his coat was silky soft! Only slight delay of 15 mins due to Seattle traffic.',
    createdAt: '2026-09-18T16:00:00Z',
    status: 'Published',
  },
  {
    id: 'rev_4',
    bookingId: 'bk_dispute_4',
    providerId: 'prov_sarah_jenkins',
    providerName: 'Sarah Jenkins',
    serviceName: 'Dog Walking',
    userId: 'usr_samantha_reed',
    userName: 'Samantha Reed',
    userAvatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&q=80&w=400',
    rating: 2,
    comment: 'Walker arrived slightly late and did not return my leash to the front hook. Requesting review from admin team.',
    createdAt: '2026-09-21T18:45:00Z',
    status: 'Reported',
    reportedReason: 'Service timeliness & equipment placement complaint.',
  },
];

// Configurable Platform & Safety Settings
export const initialPlatformSettings: PlatformSettings = {
  safeZoneWarningThresholdMeters: 100,
  emergencyCountdownDurationSeconds: 40,
  accidentDetectionTimeoutSeconds: 25,
  platformCommissionPercent: 10,
  satelliteRefreshIntervalSeconds: 3,
  autoDispatchUnits: true,
  supportEmergencyHotline: '+1 (800) 555-PET-SOS',
};

// Admin Platform Broadcasts
export const initialAdminBroadcasts: AdminBroadcastNotification[] = [
  {
    id: 'bc_01',
    title: 'Midday Heat Advisory Protocols',
    message: 'All dog walkers are required to carry hydration flasks and pause every 20 mins as temperatures exceed 26°C.',
    category: 'Safety',
    targetAudience: 'ACTIVE_WALKERS',
    createdAt: '2026-09-24T08:00:00Z',
    sentCount: 38,
    status: 'Sent',
  },
  {
    id: 'bc_02',
    title: 'Smart Collar Telemetry Upgrade v4.2',
    message: 'Smart collar satellite synchronization latency has been reduced to sub-300ms across Seattle and Portland zones.',
    category: 'System',
    targetAudience: 'ALL_USERS',
    createdAt: '2026-09-22T10:00:00Z',
    sentCount: 1420,
    status: 'Sent',
  },
];

// Admin Audit Logs
export const initialAuditLogs: AdminAuditLog[] = [
  {
    id: 'log_01',
    action: 'GEOFENCE_CALIBRATION',
    targetType: 'SafeZone',
    targetId: 'sz_milo_oakwood',
    adminName: 'Marcus Vance',
    timestamp: '2026-09-25T07:15:00Z',
    details: 'Verified Oakwood Park geofence boundary precision at 1.0 km radius.',
  },
  {
    id: 'log_02',
    action: 'PROVIDER_CREDENTIAL_CHECK',
    targetType: 'Provider',
    targetId: 'prov_liam_walker',
    adminName: 'Marcus Vance',
    timestamp: '2026-09-24T14:30:00Z',
    details: 'Applicant background check cleared. Pending manual interview approval.',
  },
];
