/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { ServiceReport, WalkReport, TrainingReport, GroomingReport, BoardingReport } from '../types/reports.ts';

export const initialServiceReports: ServiceReport[] = [
  // 1. Dog Walk Report for Bruno
  {
    id: 'rep_bruno_walk_01',
    bookingId: 'bk_bruno_walk_01',
    bookingRef: 'PC-WLK-8821',
    serviceType: 'DOG_WALKER',
    serviceTitle: 'Afternoon Neighborhood Trek',
    petId: 'pet_bruno',
    petName: 'Bruno',
    petBreed: 'Golden Retriever',
    petPhotoUrl: 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&q=80&w=400',
    providerId: 'prov_vikram_sharma',
    providerName: 'Vikram Sharma',
    providerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400',
    providerRoleTitle: 'Verified Canine Captain & Handler',
    date: 'Sep 25, 2026',
    startTime: '05:30 PM',
    endTime: '06:02 PM',
    durationMinutes: 32,
    distanceKm: 1.42,
    avgPace: "14'22\" /km",
    safeZoneCompliancePct: 100,
    safeZoneBreaches: 0,
    safeZoneRadiusM: 1000,
    waterBreaks: 2,
    pottyEvents: {
      pee: 2,
      poop: 1,
      timestamps: ['05:38 PM', '05:46 PM', '05:54 PM'],
    },
    walkNotes:
      'Bruno had a fantastic walk! He was very responsive to leash commands, walked at a steady joyful pace through Oakwood Park, and stayed safely within the 1.0 km geofence. Offered fresh water twice. Poop was cleaned up promptly and bagged.',
    photos: [
      {
        url: 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&q=80&w=600',
        caption: 'Bruno resting in shaded lawn at Oakwood Park',
        time: '05:45 PM',
      },
      {
        url: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&q=80&w=600',
        caption: 'Hydration break: Drank ~200ml filtered water happily',
        time: '05:52 PM',
      },
      {
        url: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&q=80&w=600',
        caption: 'Ready for home handover with tail wagging',
        time: '06:01 PM',
      },
    ],
    route: {
      startAddress: '424 Elm Crest Ave, Seattle',
      endAddress: '424 Elm Crest Ave, Seattle',
      waypoints: [
        { lat: 37.7749, lng: -122.4194, label: 'Start Handover', time: '05:30 PM', type: 'start' },
        { lat: 37.7758, lng: -122.4182, label: 'Elm Tree Trail', time: '05:38 PM', type: 'waypoint' },
        { lat: 37.7772, lng: -122.4169, label: 'Oakwood Park Fountain (Water Break)', time: '05:45 PM', type: 'water' },
        { lat: 37.7765, lng: -122.4151, label: 'Meadow Loop (Potty Break)', time: '05:54 PM', type: 'potty' },
        { lat: 37.7749, lng: -122.4194, label: 'Completed Home Arrival', time: '06:02 PM', type: 'end' },
      ],
    },
    notes: 'Walk completed safely with zero incidents. Safe zone was respected at all times.',
    rating: 5,
    reviewComment: 'Vikram is the absolute best walker! Punctual, communicative, and Bruno adores him.',
    createdAt: '2026-09-25T18:03:00Z',
  } as WalkReport,

  // 2. Training Session Report for Bruno
  {
    id: 'rep_bruno_train_02',
    bookingId: 'bk_bruno_train_02',
    bookingRef: 'PC-TRN-4419',
    serviceType: 'DOG_TRAINER',
    serviceTitle: 'Obedience & Impulse Mastery',
    petId: 'pet_bruno',
    petName: 'Bruno',
    petBreed: 'Golden Retriever',
    petPhotoUrl: 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&q=80&w=400',
    providerId: 'prov_vikram_sharma',
    providerName: 'Vikram Sharma',
    providerAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400',
    providerRoleTitle: 'Certified Canine Behaviorist (CPDT-KA)',
    date: 'Sep 22, 2026',
    startTime: '10:00 AM',
    endTime: '10:48 AM',
    durationMinutes: 48,
    sessionNumber: 3,
    totalSessions: 6,
    moduleTitle: 'Level 2: Long-Distance Recall & Loose-Leash Heel',
    trainingGoals: [
      'Proof emergency recall against outdoor distractions (tennis balls, other dogs)',
      'Extend sit-stay duration up to 90 seconds from 20 ft distance',
      'Reduce leash pulling on sidewalk transitions',
    ],
    exercisesCompleted: [
      {
        id: 'ex_1',
        name: 'Long-Line Recall ("Come")',
        target: 'Respond within 3s on first cue',
        accuracyPercent: 70,
        status: 'Proficient',
        notes: 'Great response speed. Needed a repeat cue only once when a bicycle whizzed past.',
      },
      {
        id: 'ex_2',
        name: 'Duration Sit & Stay',
        target: 'Maintain position 90s at 20 ft',
        accuracyPercent: 85,
        status: 'Mastered',
        notes: 'Held position rock solid! Showed fantastic patience and eye contact.',
      },
      {
        id: 'ex_3',
        name: 'Heel With Pace Changes',
        target: 'Shoulder at handler knee during fast/slow transitions',
        accuracyPercent: 55,
        status: 'Needs Practice',
        notes: 'Good baseline. Tends to surge forward on fast stops. Will focus on pivot turns next session.',
      },
    ],
    skillProgress: [
      {
        skill: 'Recall',
        currentPercent: 70,
        previousPercent: 50,
        targetPercent: 100,
      },
      {
        skill: 'Stay',
        currentPercent: 85,
        previousPercent: 70,
        targetPercent: 100,
      },
      {
        skill: 'Heel',
        currentPercent: 55,
        previousPercent: 40,
        targetPercent: 100,
      },
      {
        skill: 'Leave It',
        currentPercent: 80,
        previousPercent: 65,
        targetPercent: 100,
      },
    ],
    sessionHistory: [
      {
        sessionNumber: 1,
        date: 'Sep 08, 2026',
        durationMinutes: 45,
        skills: [
          { skill: 'Recall', score: 35 },
          { skill: 'Stay', score: 50 },
          { skill: 'Heel', score: 25 },
        ],
        summary: 'Foundation baseline assessment and reward marker loading.',
      },
      {
        sessionNumber: 2,
        date: 'Sep 15, 2026',
        durationMinutes: 45,
        skills: [
          { skill: 'Recall', score: 50 },
          { skill: 'Stay', score: 70 },
          { skill: 'Heel', score: 40 },
        ],
        summary: 'Introduction of distraction tolerance and long leash work.',
      },
      {
        sessionNumber: 3,
        date: 'Sep 22, 2026',
        durationMinutes: 48,
        skills: [
          { skill: 'Recall', score: 70 },
          { skill: 'Stay', score: 85 },
          { skill: 'Heel', score: 55 },
        ],
        summary: 'Significant gains in Stay (+15%) and Recall (+20%). Excellent focus today.',
      },
    ],
    trainerNotes:
      'Bruno was eager to learn and highly food motivated today. His Stay is becoming rock-solid, and his recall improved dramatically from Session 2. Continue 5-minute daily micro-drills before mealtime.',
    homeworkRecommendations: [
      'Practice 3x reps of "Come" across the hallway before offering dinner',
      'Keep heel practice short (2 minutes max) and reward immediately when shoulder aligns',
      'Use high-value salmon treats only for recall practice to build intense enthusiasm',
    ],
    photos: [
      {
        url: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?auto=format&fit=crop&q=80&w=600',
        caption: 'Bruno executing a steady 20-foot Stay drill',
        time: '10:18 AM',
      },
      {
        url: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&q=80&w=600',
        caption: 'High-five reward following flawless recall drill',
        time: '10:35 AM',
      },
    ],
    notes: 'Completed session 3 of 6. On schedule for Certificate of Good Canine Citizenship.',
    rating: 5,
    reviewComment: 'Remarkable difference in Bruno’s recall after only 3 sessions. Vikram explains methods so clearly.',
    createdAt: '2026-09-22T11:00:00Z',
  } as TrainingReport,

  // 3. Grooming Report for Bruno
  {
    id: 'rep_bruno_groom_03',
    bookingId: 'bk_bruno_groom_03',
    bookingRef: 'PC-GRM-9102',
    serviceType: 'PET_GROOMER',
    serviceTitle: 'Full Spa Bath, Coat Contour & Nail Care',
    petId: 'pet_bruno',
    petName: 'Bruno',
    petBreed: 'Golden Retriever',
    petPhotoUrl: 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&q=80&w=400',
    providerId: 'prov_chloe_rivera',
    providerName: 'Chloe Rivera',
    providerAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=400',
    providerRoleTitle: 'Master Canine Stylist & Fear-Free Certified',
    date: 'Sep 15, 2026',
    startTime: '02:00 PM',
    endTime: '03:15 PM',
    durationMinutes: 75,
    servicesCompleted: [
      'Hypoallergenic Oatmeal Hydro-Massage Bath',
      'Dual-Phase Undercoat De-shedding Blowout',
      'Hand Scissored Paw Feathering & Contour Trim',
      'Precision Nail Trimming & Smooth Dremel Filing',
      'Organic Lavender Ear Cleaning & Hygiene Flush',
      'Shea Butter Paw Balm Application',
    ],
    coatCondition: {
      condition: 'Healthy & Glossy',
      shampooUsed: 'All-Natural Colloidal Oatmeal & Aloe Vera Shampoo',
      sheddingLevel: 'Moderate',
      notes: 'Coat is in superb condition with minimal mats behind the ears which were gently brushed out.',
    },
    nailTrimming: {
      completed: true,
      method: 'Clipped & Smooth Dremel Rounded',
      pawBalmApplied: true,
    },
    bath: {
      shampoo: 'Oatmeal & Aloe Vera Gentle Cleanser',
      hypoallergenic: true,
      conditionerApplied: true,
      blowDryStyle: 'Warm High-Velocity De-shedding Airflow',
    },
    haircut: {
      style: 'Golden Retriever Standard Summer Outline',
      guardLength: 'Natural scissor blend with clean paw pads',
      sanitaryTrim: true,
    },
    earCleaning: {
      completed: true,
      condition: 'Clean, healthy pink, zero signs of redness or yeast',
      notes: 'Gently flushed with witch-hazel calming rinse.',
    },
    specialObservations:
      'Bruno was very cooperative in the bath! Mild sensitivity on rear right ticklish paw pads, handled with gentle reassurance. Skin is clear with no flea or tick presence.',
    beforePhotos: [
      {
        url: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&q=80&w=600',
        label: 'Before Grooming',
        description: 'Overgrown paw pads, dust from park walks, and undercoat shedding',
      },
    ],
    afterPhotos: [
      {
        url: 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&q=80&w=600',
        label: 'After Grooming',
        description: 'Silky smooth golden sheen, trimmed feathering, and polished neat paws',
      },
    ],
    groomerNotes:
      'Bruno smelled delightful (fresh cucumber melon) and loved the blow dry massage. Coat received a light silk spray for extra shine.',
    notes: 'Full spa treatment completed with zero stress.',
    rating: 5,
    reviewComment: 'Chloe made Bruno look like a show champion! The paw pad trimming is immaculate.',
    createdAt: '2026-09-15T15:20:00Z',
  } as GroomingReport,

  // 4. Boarding Report for Bruno
  {
    id: 'rep_bruno_board_04',
    bookingId: 'bk_bruno_board_04',
    bookingRef: 'PC-BRD-1277',
    serviceType: 'PET_BOARDING',
    serviceTitle: 'Overnight Luxury Boarding & Play Stay',
    petId: 'pet_bruno',
    petName: 'Bruno',
    petBreed: 'Golden Retriever',
    petPhotoUrl: 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&q=80&w=400',
    providerId: 'prov_priya_nair',
    providerName: 'Priya Nair',
    providerAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=400',
    providerRoleTitle: 'Licensed Boarding Caretaker & Facility Host',
    date: 'Sep 08, 2026',
    checkIn: 'Sep 07, 2026 · 09:00 AM',
    checkOut: 'Sep 08, 2026 · 04:30 PM',
    totalStayHours: 31.5,
    durationMinutes: 31.5 * 60,
    suiteType: 'Sunny Meadow Deluxe Suite',
    meals: [
      {
        time: 'Sep 07 · 09:30 AM',
        mealType: 'Breakfast',
        foodType: 'Prescription Organic Salmon Kibble (1.5 cups)',
        portionsEatenPct: 100,
        notes: 'Ate enthusiastically, drank plenty of fresh water.',
      },
      {
        time: 'Sep 07 · 06:00 PM',
        mealType: 'Dinner',
        foodType: 'Salmon kibble with 1 tbsp bone broth topper',
        portionsEatenPct: 100,
        notes: 'Finished bowl within 4 minutes. Relaxed digest period followed.',
      },
      {
        time: 'Sep 08 · 09:00 AM',
        mealType: 'Breakfast',
        foodType: 'Salmon kibble (1.5 cups) + frozen pumpkin chew',
        portionsEatenPct: 100,
        notes: 'Great appetite. Normal digestion.',
      },
    ],
    activities: [
      {
        time: 'Sep 07 · 11:00 AM',
        title: 'Group Agility & Ball Play',
        durationMinutes: 45,
        description: 'Played fetch with two golden buddies in the turf pen.',
        mood: 'Playful',
      },
      {
        time: 'Sep 07 · 03:30 PM',
        title: 'Sensory Enrichment & Snuffle Mat',
        durationMinutes: 30,
        description: 'Solved puzzle treat toys, very focused and calm.',
        mood: 'Relaxed',
      },
      {
        time: 'Sep 08 · 10:30 AM',
        title: 'Outdoor Garden Romp & Splash Pad',
        durationMinutes: 40,
        description: 'Splashed happily in the shallow cool wading pool.',
        mood: 'Energetic',
      },
    ],
    walks: [
      {
        time: 'Sep 07 · 01:15 PM',
        distanceKm: 1.1,
        durationMinutes: 25,
        safeZoneCompliancePct: 100,
        walkerName: 'Priya Nair',
      },
      {
        time: 'Sep 07 · 08:30 PM',
        distanceKm: 0.8,
        durationMinutes: 20,
        safeZoneCompliancePct: 100,
        walkerName: 'Priya Nair',
      },
      {
        time: 'Sep 08 · 07:30 AM',
        distanceKm: 1.3,
        durationMinutes: 30,
        safeZoneCompliancePct: 100,
        walkerName: 'Priya Nair',
      },
    ],
    photos: [
      {
        url: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&q=80&w=600',
        caption: 'Bruno making friends in the safe fenced garden',
        time: 'Sep 07 · 11:20 AM',
      },
      {
        url: 'https://images.unsplash.com/photo-1537151625747-768eb6cf92b2?auto=format&fit=crop&q=80&w=600',
        caption: 'Cozy evening snooze on his orthopedic fleece cot',
        time: 'Sep 07 · 09:45 PM',
      },
      {
        url: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?auto=format&fit=crop&q=80&w=600',
        caption: 'Morning sunbathing before checkout handover',
        time: 'Sep 08 · 02:00 PM',
      },
    ],
    caregiverNotes:
      'Bruno was an absolute delight to host! He slept peacefully throughout the night, enjoyed all three chef-supervised walks, and got along marvelously with our team. We look forward to welcoming him back anytime!',
    notes: '31.5 hours completed with 100% health & happiness score.',
    rating: 5,
    reviewComment: 'Priya sent photo updates all day and night. Bruno came home calm, happy, and well rested.',
    createdAt: '2026-09-08T16:40:00Z',
  } as BoardingReport,

  // 5. Grooming Report for Milo (linked to bk_grooming_past_03)
  {
    id: 'rep_milo_groom_05',
    bookingId: 'bk_grooming_past_03',
    bookingRef: 'PC-GRM-3310',
    serviceType: 'PET_GROOMER',
    serviceTitle: 'Deluxe Spa & Deshedding Treatment',
    petId: 'pet_milo',
    petName: 'Milo',
    petBreed: 'Golden Retriever',
    petPhotoUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCUuQBqBW7jAgvPaf0dm9LxrCEv9Q3L_DyJbjPZweOP62mkqtSQPixUMJLncp0NpElorXOg-p_YisXvtzXfTNqFsBG25ZU9Z9ihdE4058cJ0lITdZ64Okc87t2PDjDxgu0cnVIxZVNHclEB3A2NieX4MOSjjQwWqStQSYaWLbyidVFwtGzgQNI8kWWcz8N2wzqnmchHerCHmiy52SUkrueT70vtdMvOgVP1Oksny7rwXx1emN4y7pU0',
    providerId: 'prov_chloe_groom',
    providerName: 'Chloe Rivera',
    providerAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=400',
    providerRoleTitle: 'Master Grooming Stylist',
    date: 'Sep 18, 2026',
    startTime: '02:00 PM',
    endTime: '03:30 PM',
    durationMinutes: 90,
    servicesCompleted: [
      'Hypoallergenic Tea Tree Soak',
      'Dual Velocity De-shedding Sweep',
      'Nail Dremel & Organic Balm',
      'Ear Deep Hygiene Cleanse',
      'Feathering Scissor Styling',
    ],
    coatCondition: {
      condition: 'Healthy & Glossy',
      shampooUsed: 'Hypoallergenic Tea Tree & Silk Protein Formula',
      sheddingLevel: 'Moderate',
      notes: 'Removed ~250g of trapped summer undercoat. Skin respiration noticeably improved.',
    },
    nailTrimming: {
      completed: true,
      method: 'Clipped & Smooth Dremel',
      pawBalmApplied: true,
    },
    bath: {
      shampoo: 'Tea Tree & Silk Formula',
      hypoallergenic: true,
      conditionerApplied: true,
      blowDryStyle: 'Warm high velocity',
    },
    haircut: {
      style: 'Golden Retriever Feather Trim',
      guardLength: 'Hand scissored paws and sanitary area',
      sanitaryTrim: true,
    },
    earCleaning: {
      completed: true,
      condition: 'Clear, zero wax buildup',
      notes: 'Checked canal, completely dry and healthy.',
    },
    specialObservations: 'Milo was super patient during blow drying. Very fond of head massages.',
    beforePhotos: [
      {
        url: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&q=80&w=600',
        label: 'Before',
        description: 'Thick seasonal shed coat with minor paw pad tangles',
      },
    ],
    afterPhotos: [
      {
        url: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCUuQBqBW7jAgvPaf0dm9LxrCEv9Q3L_DyJbjPZweOP62mkqtSQPixUMJLncp0NpElorXOg-p_YisXvtzXfTNqFsBG25ZU9Z9ihdE4058cJ0lITdZ64Okc87t2PDjDxgu0cnVIxZVNHclEB3A2NieX4MOSjjQwWqStQSYaWLbyidVFwtGzgQNI8kWWcz8N2wzqnmchHerCHmiy52SUkrueT70vtdMvOgVP1Oksny7rwXx1emN4y7pU0',
        label: 'After',
        description: 'Silky, tangle-free coat with feather scissoring and groomed paws',
      },
    ],
    groomerNotes: 'Milo was an angel on the grooming table. Beautiful coat luster!',
    notes: 'Completed deluxe spa session.',
    rating: 5,
    reviewComment: 'Milo came back smelling divine and looking so handsome! Thank you Chloe!',
    createdAt: '2026-09-18T15:35:00Z',
  } as GroomingReport,
];
