/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import {
  ProviderProfile,
  ProviderAssignment,
  ProviderEarningsSummary,
  ProviderNotification,
  CustomerReviewForProvider,
} from './types.ts';

export const initialProviderProfile: ProviderProfile = {
  id: 'prov_vikram_01',
  name: 'Vikram Sharma',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
  phone: '+91 98450 12890',
  email: 'vikram.provider@petcare.in',
  address: '104, Palm Grove, 12th Main, Indiranagar, Bengaluru, 560038',
  rating: 4.88,
  totalReviews: 126,
  totalCompletedJobs: 318,
  experienceYears: 4,
  bio: 'Certified Canine Specialist & Dog Behaviorist. Over 4 years of professional handling experience with high-energy breeds, safe-zone walking, and leash manners training.',
  serviceTypes: ['DOG_WALKER', 'DOG_TRAINER'],
  serviceAreaRadiusKm: 6.0,
  basePricing: {
    dogWalking: 350,
    dogTraining: 850,
    petGrooming: 750,
    petBoarding: 1400,
  },
  categoryRatings: {
    professionalism: 4.9,
    petHandling: 5.0,
    punctuality: 4.8,
    serviceQuality: 4.9,
  },
  acceptanceRatePct: 96,
  completionRatePct: 99.4,
  verificationStatus: 'Verified',
  documents: [
    {
      id: 'doc_1',
      name: 'Government Photo ID (Aadhaar / Passport)',
      type: 'IDENTITY_PROOF',
      status: 'Verified',
      uploadDate: '12 Jan 2024',
    },
    {
      id: 'doc_2',
      name: 'Canine Care & Leash Handling Certification',
      type: 'PET_CERTIFICATION',
      status: 'Verified',
      uploadDate: '15 Jan 2024',
    },
    {
      id: 'doc_3',
      name: 'Police Background Verification & Address Proof',
      type: 'BACKGROUND_CHECK',
      status: 'Verified',
      uploadDate: '18 Jan 2024',
    },
  ],
};

export const sampleCustomerReviews: CustomerReviewForProvider[] = [
  {
    id: 'rev_1',
    customerName: 'Megha R.',
    customerAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80',
    petName: 'Bruno',
    serviceTitle: 'Dog Walking (30 min)',
    date: 'Today · 6:15 PM',
    rating: 5.0,
    comment: 'Bruno had an energetic and joyful walk! Vikram sent live water updates, stayed 100% inside the approved safe zone, and logged potty breaks promptly. Absolute 5-star captain!',
    categoryScores: {
      professionalism: 5.0,
      petHandling: 5.0,
      punctuality: 5.0,
      serviceQuality: 5.0,
    },
    tags: ['Super Punctual', 'Gentle Handler', 'Live GPS Updates'],
  },
  {
    id: 'rev_2',
    customerName: 'Ananya Sharma',
    customerAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80',
    petName: 'Rocky',
    serviceTitle: 'Canine Leash & Recall Training (60 min)',
    date: 'Yesterday',
    rating: 4.9,
    comment: 'Remarkable improvement in Rocky’s loose-leash walking after just one session. Vikram knows dog psychology inside out. Highly recommended!',
    categoryScores: {
      professionalism: 5.0,
      petHandling: 5.0,
      punctuality: 4.8,
      serviceQuality: 4.9,
    },
    tags: ['Expert Trainer', 'High Energy', 'Clear Homework'],
  },
  {
    id: 'rev_3',
    customerName: 'Karan & Priya',
    customerAvatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
    petName: 'Milo',
    serviceTitle: 'Overnight Pet Boarding (24 hrs)',
    date: '22 Sep 2026',
    rating: 5.0,
    comment: 'Milo felt completely at home. Secure yard, timely feeding logs, and daily video check-ins gave us complete peace of mind while away.',
    categoryScores: {
      professionalism: 5.0,
      petHandling: 5.0,
      punctuality: 5.0,
      serviceQuality: 5.0,
    },
    tags: ['Safe Boarding', 'Daily Photos', 'Loving Care'],
  },
  {
    id: 'rev_4',
    customerName: 'Rohit Kulkarni',
    customerAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    petName: 'Bella',
    serviceTitle: 'Full Hygiene Groom & Coat Styling (45 min)',
    date: '20 Sep 2026',
    rating: 4.8,
    comment: 'Bella came back smelling wonderful and fluffier than ever! Gentle with her sensitive paws during nail clipping.',
    categoryScores: {
      professionalism: 4.8,
      petHandling: 4.9,
      punctuality: 4.7,
      serviceQuality: 4.9,
    },
    tags: ['Clean & Fresh', 'Patient Grooming'],
  },
];

export const sampleIncomingRequests: Record<string, ProviderAssignment> = {
  DOG_WALKER: {
    id: 'req_walk_01',
    bookingRef: 'PC-WLK-9021',
    serviceType: 'DOG_WALKER',
    serviceTitle: 'Dog Walking (30 min)',
    customer: {
      id: 'cust_megha_01',
      name: 'Megha R.',
      phone: '+91 98765 43210',
      rating: 4.9,
      totalBookings: 14,
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80',
    },
    pet: {
      id: 'pet_bruno_01',
      name: 'Bruno',
      breed: 'Golden Retriever',
      species: 'Dog',
      ageYears: 2.5,
      weightKg: 28,
      photoUrl: 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=400&q=80',
      temperament: 'Friendly & energetic. Loves sniff breaks and grassy trails.',
      specialInstructions: 'Pull harness gently at crosswalks. Safe-zone perimeter is set to 1.0 km around customer residence.',
      allergies: 'Chicken treats (give beef or lamb treats only)',
      microchipId: '985141002348912',
    },
    pickupAddress: 'Apt 402, Green Glen Layout, 12th Main, Indiranagar',
    pickupCoords: { lat: 12.9716, lng: 77.5946 },
    distanceKm: 2.3,
    estimatedArrivalMin: 8,
    scheduledTime: '5:30 PM',
    scheduledDate: 'Today',
    durationMinutes: 30,
    estimatedEarnings: 350,
    baseEarnings: 300,
    distanceBonus: 50,
    status: 'PENDING_ACCEPTANCE',
    safeZoneRadiusMeters: 1000,
    specialRequirements: ['Leash Handling', 'Hydration Log', 'GPS Live Tracking'],
    createdAt: new Date().toISOString(),
    checklist: {
      petReceived: false,
      leashSecured: false,
      conditionChecked: false,
      safeZoneVerified: false,
    },
    liveWalkTelemetry: {
      distanceWalkedKm: 0,
      durationSeconds: 0,
      currentSpeedKmH: 3.4,
      currentPace: '12m 45s / km',
      safeZoneState: 'GREEN',
      distanceToBoundaryM: 780,
      hydrationCount: 0,
      peeCount: 0,
      poopCount: 0,
      isWalking: false,
      safeZoneCompliancePct: 100,
    },
  },
  DOG_TRAINER: {
    id: 'req_train_02',
    bookingRef: 'PC-TRN-4412',
    serviceType: 'DOG_TRAINER',
    serviceTitle: 'Canine Leash & Recall Training (60 min)',
    customer: {
      id: 'cust_ananya_02',
      name: 'Ananya Sharma',
      phone: '+91 97112 34567',
      rating: 4.85,
      totalBookings: 8,
      avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80',
    },
    pet: {
      id: 'pet_rocky_02',
      name: 'Rocky',
      breed: 'German Shepherd',
      species: 'Dog',
      ageYears: 1.2,
      weightKg: 31,
      photoUrl: 'https://images.unsplash.com/photo-1589941013453-ec89f33b5e95?auto=format&fit=crop&w=400&q=80',
      temperament: 'Intelligent, high drive, pulls when seeing squirrels or other dogs.',
      specialInstructions: 'Focus on loose leash heel walk and emergency recall command using high-value treats.',
    },
    pickupAddress: 'Villa 18, Palm Meadows, Whitefield',
    pickupCoords: { lat: 12.9698, lng: 77.7499 },
    distanceKm: 3.1,
    estimatedArrivalMin: 12,
    scheduledTime: '6:15 PM',
    scheduledDate: 'Today',
    durationMinutes: 60,
    estimatedEarnings: 850,
    baseEarnings: 750,
    distanceBonus: 100,
    status: 'PENDING_ACCEPTANCE',
    safeZoneRadiusMeters: 1500,
    specialRequirements: ['Recall Drills', 'Heel Training', 'Temperament Assessment'],
    createdAt: new Date().toISOString(),
    trainingProgress: {
      drills: [
        { id: 'd1', name: 'Eye Contact & Focus (Name Game)', completed: false },
        { id: 'd2', name: 'Loose Leash Walking (Heel)', completed: false },
        { id: 'd3', name: 'Sit & Stay with 10-pace Distraction', completed: false },
        { id: 'd4', name: 'Emergency Recall ("Come" with high reward)', completed: false },
      ],
      temperamentScore: 8,
      trainerNotes: '',
    },
  },
  PET_GROOMER: {
    id: 'req_groom_03',
    bookingRef: 'PC-GRM-8199',
    serviceType: 'PET_GROOMER',
    serviceTitle: 'Full Hygiene Groom & Coat Styling (45 min)',
    customer: {
      id: 'cust_rohit_03',
      name: 'Rohit Kulkarni',
      phone: '+91 99001 23456',
      rating: 4.95,
      totalBookings: 21,
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    },
    pet: {
      id: 'pet_bella_03',
      name: 'Bella',
      breed: 'Shih Tzu',
      species: 'Dog',
      ageYears: 3,
      weightKg: 6.5,
      photoUrl: 'https://images.unsplash.com/photo-1541599540903-216a46ca1dc0?auto=format&fit=crop&w=400&q=80',
      temperament: 'Calm and affectionate, gentle with paw handling.',
      specialInstructions: 'Use hypoallergenic shampoo, trim ear fur carefully, clip nails to safe quick.',
    },
    pickupAddress: 'Tower B - 1201, Sobha Iris, Outer Ring Road',
    pickupCoords: { lat: 12.9279, lng: 77.6271 },
    distanceKm: 1.8,
    estimatedArrivalMin: 6,
    scheduledTime: '4:00 PM',
    scheduledDate: 'Tomorrow',
    durationMinutes: 45,
    estimatedEarnings: 750,
    baseEarnings: 650,
    distanceBonus: 100,
    status: 'PENDING_ACCEPTANCE',
    safeZoneRadiusMeters: 500,
    specialRequirements: ['Nail Trim', 'Organic Bath', 'Ear Cleaning', 'Sanitary Trim'],
    createdAt: new Date().toISOString(),
    groomingProgress: {
      steps: [
        { id: 'g1', name: 'Coat De-tangling & Pre-brush', completed: false },
        { id: 'g2', name: 'Warm Hydro-Bath & Oatmeal Shampoo', completed: false },
        { id: 'g3', name: 'High-Velocity Blow Dry & Fluff', completed: false },
        { id: 'g4', name: 'Nail Clipping & Paw Pad Trim', completed: false },
        { id: 'g5', name: 'Ear Cleaning & Fresh Cologne Finish', completed: false },
      ],
      coatCondition: 'Healthy, minimal matting',
      notes: '',
    },
  },
  PET_BOARDING: {
    id: 'req_board_04',
    bookingRef: 'PC-BRD-3301',
    serviceType: 'PET_BOARDING',
    serviceTitle: 'Overnight Pet Boarding (24 hrs)',
    customer: {
      id: 'cust_karan_04',
      name: 'Karan & Priya',
      phone: '+91 98840 99881',
      rating: 5.0,
      totalBookings: 6,
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
    },
    pet: {
      id: 'pet_milo_04',
      name: 'Milo',
      breed: 'Beagle',
      species: 'Dog',
      ageYears: 4,
      weightKg: 13,
      photoUrl: 'https://images.unsplash.com/photo-1537151625747-768eb6cf92b2?auto=format&fit=crop&w=400&q=80',
      temperament: 'Friendly hound dog, curious sniffer, loves chew toys.',
      specialInstructions: 'Feed 1 cup kibble at 8:00 AM and 8:00 PM. Needs evening backyard play. Keep gates latched.',
    },
    pickupAddress: 'House 55, Defence Colony, Halasuru',
    pickupCoords: { lat: 12.9784, lng: 77.6257 },
    distanceKm: 4.2,
    estimatedArrivalMin: 15,
    scheduledTime: '7:00 PM',
    scheduledDate: 'Today',
    durationMinutes: 1440,
    estimatedEarnings: 1400,
    baseEarnings: 1300,
    distanceBonus: 100,
    status: 'PENDING_ACCEPTANCE',
    safeZoneRadiusMeters: 500,
    specialRequirements: ['Secure Fenced Area', 'Twice Daily Meals', 'Evening Playtime'],
    boardingDates: {
      checkInDate: '25 Sep 2026',
      checkOutDate: '26 Sep 2026',
      checkInTime: '7:00 PM',
      checkOutTime: '7:00 PM',
      durationDays: 1,
    },
    createdAt: new Date().toISOString(),
    boardingProgress: {
      checkInTime: '7:00 PM',
      mealsGiven: [
        { time: '8:00 PM', item: 'Evening Royal Canin Kibble (1 cup)' }
      ],
      medicationAdministered: false,
      dailyExerciseMin: 45,
      notes: 'Settled in warmly, curled up with comfort blanket.',
    },
  },
};

export const initialScheduledAssignments: ProviderAssignment[] = [
  {
    id: 'sched_01',
    bookingRef: 'PC-WLK-7819',
    serviceType: 'DOG_WALKER',
    serviceTitle: 'Evening Neighborhood Walk',
    customer: {
      id: 'cust_sarah_09',
      name: 'Sarah Jenkins',
      phone: '+91 99887 66554',
      rating: 4.95,
      totalBookings: 19,
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80',
    },
    pet: {
      id: 'pet_cooper_09',
      name: 'Cooper',
      breed: 'Golden Retriever',
      species: 'Dog',
      ageYears: 3,
      weightKg: 29,
      photoUrl: 'https://images.unsplash.com/photo-1537151625747-768eb6cf92b2?auto=format&fit=crop&w=400&q=80',
      temperament: 'Very friendly, steady walker.',
      specialInstructions: 'Safe zone is 1.2 km around apartment.',
    },
    pickupAddress: 'Prestige Ozone, Whitefield Main Road',
    pickupCoords: { lat: 12.9698, lng: 77.7499 },
    distanceKm: 2.1,
    estimatedArrivalMin: 7,
    scheduledTime: '7:30 PM',
    scheduledDate: 'Today',
    durationMinutes: 45,
    estimatedEarnings: 450,
    baseEarnings: 400,
    distanceBonus: 50,
    status: 'ACCEPTED',
    safeZoneRadiusMeters: 1200,
    specialRequirements: ['Evening Walk', 'Hydration Log'],
    createdAt: '2026-09-25T10:00:00Z',
    checklist: {
      petReceived: false,
      leashSecured: false,
      conditionChecked: false,
      safeZoneVerified: false,
    },
  },
  {
    id: 'sched_02',
    bookingRef: 'PC-TRN-8820',
    serviceType: 'DOG_TRAINER',
    serviceTitle: 'Puppy Socialization & Leash Discipline',
    customer: {
      id: 'cust_rajesh_10',
      name: 'Rajesh Nair',
      phone: '+91 91234 56789',
      rating: 4.88,
      totalBookings: 5,
      avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=200&q=80',
    },
    pet: {
      id: 'pet_simba_10',
      name: 'Simba',
      breed: 'Golden Retriever',
      species: 'Dog',
      ageYears: 0.8,
      weightKg: 18,
      photoUrl: 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=400&q=80',
      temperament: 'Playful puppy, easily excited by pedestrians.',
      specialInstructions: 'Bring training clicker and treat pouch.',
    },
    pickupAddress: 'Villa 45, Adarsh Palm Retreat, Bellandur',
    pickupCoords: { lat: 12.9279, lng: 77.6711 },
    distanceKm: 3.8,
    estimatedArrivalMin: 14,
    scheduledTime: '9:00 AM',
    scheduledDate: 'Tomorrow',
    durationMinutes: 60,
    estimatedEarnings: 850,
    baseEarnings: 750,
    distanceBonus: 100,
    status: 'ACCEPTED',
    safeZoneRadiusMeters: 1000,
    specialRequirements: ['Puppy Obedience', 'Positive Reinforcement'],
    createdAt: '2026-09-25T11:00:00Z',
  },
];

export const initialAssignmentHistory: ProviderAssignment[] = [
  // Completed
  {
    id: 'hist_01',
    bookingRef: 'PC-WLK-6611',
    serviceType: 'DOG_WALKER',
    serviceTitle: 'Morning Cardio Walk',
    customer: {
      id: 'cust_aditi_11',
      name: 'Aditi Varma',
      phone: '+91 98451 12345',
      rating: 5.0,
      totalBookings: 32,
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
    },
    pet: {
      id: 'pet_leo_11',
      name: 'Leo',
      breed: 'Beagle',
      species: 'Dog',
      ageYears: 3,
      weightKg: 12,
      photoUrl: 'https://images.unsplash.com/photo-1537151625747-768eb6cf92b2?auto=format&fit=crop&w=400&q=80',
      temperament: 'Curious sniffer, polite with dogs.',
      specialInstructions: 'Safe zone 1.0 km radius.',
    },
    pickupAddress: '14th Cross, 100ft Road, Indiranagar',
    pickupCoords: { lat: 12.9716, lng: 77.6412 },
    distanceKm: 1.5,
    estimatedArrivalMin: 5,
    scheduledTime: '7:00 AM',
    scheduledDate: 'Today',
    durationMinutes: 32,
    estimatedEarnings: 400,
    baseEarnings: 300,
    distanceBonus: 50,
    tip: 50,
    status: 'COMPLETED',
    safeZoneRadiusMeters: 1000,
    specialRequirements: ['Completed Safely'],
    createdAt: '2026-09-25T06:30:00Z',
    notes: 'Leo enjoyed the park trail. 1 Pee break, 1 Poop break recorded. Safe zone compliance 100%.',
    ratingReceived: 5.0,
    reviewComment: 'Leo was thoroughly happy and well exercised. Vikram is our favorite walker!',
  },
  {
    id: 'hist_02',
    bookingRef: 'PC-TRN-5541',
    serviceType: 'DOG_TRAINER',
    serviceTitle: 'Heel & Socialization Training',
    customer: {
      id: 'cust_sid_12',
      name: 'Siddharth Menon',
      phone: '+91 97410 98765',
      rating: 4.9,
      totalBookings: 12,
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    },
    pet: {
      id: 'pet_shadow_12',
      name: 'Shadow',
      breed: 'Labrador Retriever',
      species: 'Dog',
      ageYears: 2,
      weightKg: 30,
      photoUrl: 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=400&q=80',
      temperament: 'Energetic, eager to please.',
      specialInstructions: 'Loose leash drills in community park.',
    },
    pickupAddress: '401, Ferns Residency, Doddanekkundi',
    pickupCoords: { lat: 12.9716, lng: 77.6912 },
    distanceKm: 3.2,
    estimatedArrivalMin: 10,
    scheduledTime: '11:00 AM',
    scheduledDate: 'Today',
    durationMinutes: 60,
    estimatedEarnings: 900,
    baseEarnings: 750,
    distanceBonus: 100,
    tip: 50,
    status: 'COMPLETED',
    safeZoneRadiusMeters: 1200,
    specialRequirements: ['Completed Safely'],
    createdAt: '2026-09-25T10:30:00Z',
    notes: 'Shadow achieved 9/10 heel consistency with distraction. Recommended owner continue 5 min daily reinforcement.',
    ratingReceived: 4.9,
    reviewComment: 'Shadow stopped pulling on leash in just one session. Super impressed.',
  },
  {
    id: 'hist_03',
    bookingRef: 'PC-WLK-3210',
    serviceType: 'DOG_WALKER',
    serviceTitle: 'Afternoon Leash Walk',
    customer: {
      id: 'cust_priya_13',
      name: 'Priya Sundaram',
      phone: '+91 99160 55443',
      rating: 4.9,
      totalBookings: 8,
      avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80',
    },
    pet: {
      id: 'pet_daisy_13',
      name: 'Daisy',
      breed: 'Cocker Spaniel',
      species: 'Dog',
      ageYears: 4,
      weightKg: 11,
      photoUrl: 'https://images.unsplash.com/photo-1541599540903-216a46ca1dc0?auto=format&fit=crop&w=400&q=80',
      temperament: 'Gentle, loves sniffing flowers.',
      specialInstructions: 'Keep pace moderate.',
    },
    pickupAddress: '102, Laurel Apts, Koramangala 4th Block',
    pickupCoords: { lat: 12.9352, lng: 77.6245 },
    distanceKm: 2.0,
    estimatedArrivalMin: 7,
    scheduledTime: '2:30 PM',
    scheduledDate: 'Today',
    durationMinutes: 30,
    estimatedEarnings: 350,
    baseEarnings: 300,
    distanceBonus: 50,
    status: 'COMPLETED',
    safeZoneRadiusMeters: 800,
    specialRequirements: ['Completed Safely'],
    createdAt: '2026-09-25T14:00:00Z',
    notes: 'Daisy had a pleasant 1.2 km walk. Well hydrated and resting happily at home.',
    ratingReceived: 5.0,
    reviewComment: 'Daisy loves Vikram so much! Always punctual and super caring.',
  },

  // Cancelled
  {
    id: 'hist_04',
    bookingRef: 'PC-WLK-1192',
    serviceType: 'DOG_WALKER',
    serviceTitle: 'Evening Walk',
    customer: {
      id: 'cust_rahul_14',
      name: 'Rahul Sen',
      phone: '+91 98111 22334',
      rating: 4.8,
      totalBookings: 4,
      avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=200&q=80',
    },
    pet: {
      id: 'pet_buster_14',
      name: 'Buster',
      breed: 'Boxer',
      species: 'Dog',
      ageYears: 3,
      weightKg: 26,
      photoUrl: 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=400&q=80',
      temperament: 'High energy',
      specialInstructions: 'Check collar tightness',
    },
    pickupAddress: '303, Sunrise Apts, Domlur',
    pickupCoords: { lat: 12.9609, lng: 77.6387 },
    distanceKm: 2.8,
    estimatedArrivalMin: 9,
    scheduledTime: '6:30 PM',
    scheduledDate: '24 Sep 2026',
    durationMinutes: 30,
    estimatedEarnings: 100, // Cancellation fee credited to Captain
    baseEarnings: 100,
    distanceBonus: 0,
    status: 'CANCELLED',
    safeZoneRadiusMeters: 1000,
    specialRequirements: ['Cancelled by Customer'],
    createdAt: '2026-09-24T17:45:00Z',
    cancellationReason: 'Sudden rainstorm in Domlur. ₹100 Captain convenience fee credited.',
  },

  // Declined
  {
    id: 'hist_05',
    bookingRef: 'PC-TRN-7731',
    serviceType: 'DOG_TRAINER',
    serviceTitle: 'Aggression Mitigation Training',
    customer: {
      id: 'cust_manish_15',
      name: 'Manish Gupta',
      phone: '+91 99880 11223',
      rating: 4.6,
      totalBookings: 2,
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    },
    pet: {
      id: 'pet_tyson_15',
      name: 'Tyson',
      breed: 'Rottweiler',
      species: 'Dog',
      ageYears: 4,
      weightKg: 42,
      photoUrl: 'https://images.unsplash.com/photo-1589941013453-ec89f33b5e95?auto=format&fit=crop&w=400&q=80',
      temperament: 'Protective, needs muzzle',
      specialInstructions: 'Outside coverage radius (11 km away)',
    },
    pickupAddress: 'Sector 2, HSR Layout (11.2 km away)',
    pickupCoords: { lat: 12.9116, lng: 77.6496 },
    distanceKm: 11.2,
    estimatedArrivalMin: 35,
    scheduledTime: '3:00 PM',
    scheduledDate: '23 Sep 2026',
    durationMinutes: 60,
    estimatedEarnings: 950,
    baseEarnings: 800,
    distanceBonus: 150,
    status: 'DECLINED',
    safeZoneRadiusMeters: 1500,
    specialRequirements: ['Declined by Captain'],
    createdAt: '2026-09-23T14:30:00Z',
    cancellationReason: 'Pickup location beyond active 6 km service boundary.',
  },
];

export const initialEarningsSummary: ProviderEarningsSummary = {
  todayTotal: 1650,
  todayBase: 1350,
  todayBonus: 200,
  todayTips: 100,
  todayJobsCount: 3,
  todayOnlineHours: 4.8,
  weeklyTotal: 12450,
  monthlyTotal: 48900,
  availableForPayout: 4850,
  pendingPayouts: 1650,
  dailyEarnings: [
    { day: 'Mon', date: '21 Sep', amount: 2100, jobs: 4 },
    { day: 'Tue', date: '22 Sep', amount: 1850, jobs: 3 },
    { day: 'Wed', date: '23 Sep', amount: 2400, jobs: 5 },
    { day: 'Thu', date: '24 Sep', amount: 1950, jobs: 4 },
    { day: 'Fri', date: '25 Sep (Today)', amount: 1650, jobs: 3 },
    { day: 'Sat', date: '26 Sep (Est)', amount: 2800, jobs: 6 },
    { day: 'Sun', date: '27 Sep (Est)', amount: 2600, jobs: 5 },
  ],
  recentPayouts: [
    {
      id: 'payout_101',
      amount: 7600,
      date: '21 Sep 2026',
      status: 'SUCCESS',
      bankAccount: 'HDFC Bank •• 4912 (Instant IMPS)',
    },
    {
      id: 'payout_100',
      amount: 8200,
      date: '14 Sep 2026',
      status: 'SUCCESS',
      bankAccount: 'HDFC Bank •• 4912 (Instant IMPS)',
    },
  ],
  transactions: [
    {
      id: 'tx_101',
      bookingRef: 'PC-WLK-6611',
      petName: 'Leo (Beagle)',
      serviceTitle: 'Morning Cardio Walk',
      date: 'Today · 7:35 AM',
      amount: 400,
      type: 'EARNING',
      status: 'COMPLETED',
    },
    {
      id: 'tx_102',
      bookingRef: 'PC-TRN-5541',
      petName: 'Shadow (Labrador)',
      serviceTitle: 'Heel & Socialization Training',
      date: 'Today · 12:05 PM',
      amount: 900,
      type: 'EARNING',
      status: 'COMPLETED',
    },
    {
      id: 'tx_103',
      bookingRef: 'PC-WLK-3210',
      petName: 'Daisy (Cocker Spaniel)',
      serviceTitle: 'Afternoon Leash Walk',
      date: 'Today · 3:05 PM',
      amount: 350,
      type: 'EARNING',
      status: 'COMPLETED',
    },
    {
      id: 'tx_100',
      bookingRef: 'PAYOUT-IMPS-892',
      petName: 'Wallet IMPS',
      serviceTitle: 'Withdrawal to HDFC Bank (••4912)',
      date: '21 Sep 2026',
      amount: 7600,
      type: 'WITHDRAWAL',
      status: 'COMPLETED',
    },
  ],
};

export const initialProviderNotifications: ProviderNotification[] = [
  {
    id: 'p_notif_01',
    title: 'New Service Assignment Dispatched',
    message: 'New Walk Request matched for Bruno (Golden Retriever) in Indiranagar. Tap to review.',
    timestamp: '2 mins ago',
    type: 'NEW_ASSIGNMENT',
    isRead: false,
  },
  {
    id: 'p_notif_02',
    title: 'Customer Rating Received ★★★★★',
    message: 'Megha rated you 5.0 stars for Bruno: "Bruno loved the walk! Very punctual and safe."',
    timestamp: '25 mins ago',
    type: 'RATING_RECEIVED',
    isRead: false,
  },
  {
    id: 'p_notif_03',
    title: 'Payment Credited to Wallet',
    message: '₹400 for Morning Cardio Walk (Leo) credited to your PetCare wallet including ₹50 tip.',
    timestamp: '1 hour ago',
    type: 'PAYMENT_UPDATE',
    isRead: false,
  },
  {
    id: 'p_notif_04',
    title: 'Customer Arrival Handover',
    message: 'You marked arrival at 14th Cross Indiranagar. Customer notified for pet handover.',
    timestamp: '3 hours ago',
    type: 'CUSTOMER_ARRIVAL',
    isRead: true,
  },
  {
    id: 'p_notif_05',
    title: 'Upcoming Service Reminder',
    message: 'Scheduled evening walk with Cooper (Prestige Ozone) at 7:30 PM today.',
    timestamp: '4 hours ago',
    type: 'UPCOMING_SERVICE',
    isRead: true,
  },
  {
    id: 'p_notif_06',
    title: 'Customer Message from Sarah',
    message: 'Sarah: "Cooper is wearing his blue harness today. Keys are with security."',
    timestamp: '5 hours ago',
    type: 'CUSTOMER_MESSAGE',
    isRead: true,
  },
  {
    id: 'p_notif_07',
    title: 'Assignment Cancelled Notice',
    message: 'Walk with Buster cancelled by customer due to rain. ₹100 inconvenience fee credited.',
    timestamp: 'Yesterday',
    type: 'ASSIGNMENT_CANCELLED',
    isRead: true,
  },
  {
    id: 'p_notif_08',
    title: 'Safe Zone Warning Test Cleared',
    message: 'GPS telemetry confirmed walker returned safely inside 1.0 km perimeter.',
    timestamp: 'Yesterday',
    type: 'SAFETY_WARNING',
    isRead: true,
  },
];
